export { default as Root } from './Root'
export { default as Home } from './Home'
export { default as Story } from './Story'
export { default as Post } from './Post'
export { default as NotFound } from './NotFound'